namespace MiniShipDelivery.Components.Tilemap
{
    public enum TilemapPart
    {
        CharacterStandFront = 1,
        CharacterStandLeft = 2,
        CharacterStandRight = 3,
        CharacterStandBack = 4,
        CharacterWalkLeftFoodFront = 5,
        CharacterWalkLeftFoodBack = 6,
        CharacterWalkLeftFoodLeft = 7,
        CharacterWalkLeftFoodRight = 8,
        CharacterWalkRightFoodFront = 9,
        CharacterWalkRightFoodBack = 10,
        CharacterWalkRightFoodLeft = 11,
        CharacterWalkRightFoodRight = 12,
        RoomGray_TopLeft = 13,
        RoomGray_TopMiddle = 14,
        RoomGray_TopRight = 15,
        RoomGray_MiddleLeft = 16,
        RoomGray_MiddleMiddle = 17,
        RoomGray_MiddleRight = 18,
        RoomGray_DownLeft = 19,
        RoomGray_DownMiddle = 20,
        RoomGray_DownRight = 21,
        EmoteHappy = 22,
        EmoteSad = 23,
        EmoteAngry = 24,
        EmoteSurprised = 25,
        EmoteSleepy = 26,
        EmoteSick = 27,
        EmoteConfused = 28,
        EmoteLove = 29,
        EmoteQuestion = 30,
        EmoteExclamation = 31,
        EmoteMusic = 32,
        EmoteZzz = 33,
        EmoteDotDotDot = 34,
        EmoteLoveDouble = 35
    }
}